name: Update README

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'  # 최신 안정 버전으로 설정

      - name: Install Bundler and Linguist
        run: |
          gem install bundler
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'github-linguist', '~> 7.11.0'" >> Gemfile
          bundle install
          bundle exec linguist --version  # linguist가 올바르게 설치되었는지 확인

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python 버전 설정

      - name: Install Pygithub
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Apply .gitattributes and Run Linguist
        run: |
          cat .gitattributes
          bundle exec linguist --json > languages.json

      - name: Update README.md
        run: |
          python update_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
